### ISSUE TITLE
Unifying usage of "parameters" and "variables".

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#113]
Shall we use a convention of how we call the things one can optimize with PennyLane? Josh and I decided to use "Variables", because there might be fixed "circuit parameters". Only downside, "vars" is a reserved keyword in python it seems.

**Comment by josh146** [comment]
As the docs are now much more stable, I am closing this issue - feel free to reopen/make a new issue if inconsistencies remain.
