### ISSUE TITLE
todos in codebase

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane#123]
- [ ] doc/zreferences.rst: add uncited refs to docs?
- [ ] expval.cv.py:176: check for heisenberg rep of homodyne measurement
- [ ] ops/cv.py:537: put Heisenberg reps of state preparations in docstrings?

Other todos (not explicitly in docs):
- [x] update Development status

DAG related todos (future release): 
- [ ] tests/test_qnode.py:125,567
- [ ] qnode.py:372,402,431,754

Other stuff for future releases:
- [ ] ops/cv.py:27,29: todos related to gradient recipes/computations for CV ops

**Comment by josh146** [comment]
Closing this issue as it is outdated. Current TODOs can be viewed by running pylint on the pennylane folder, or by viewing [ignored issues on CodeFactor](https://www.codefactor.io/repository/github/xanaduai/pennylane/ignoredissues?page=1).
