### ISSUE TITLE
Example Variational Classifier no batching when learning parity

### ISSUE THREAD

**Issue by chMoussa** [XanaduAI/pennylane#128]
Hello,

Just a quick fix. I noticed in the code example of the variational classifier that you do not batch for the learning of the parity function: 

`for it in range(25):

    # Update the weights by one optimizer step
    batch_index = np.random.randint(0, len(X), (batch_size, ))
    X_batch = X[batch_index]
    Y_batch = Y[batch_index]
    var = opt.step(lambda v: cost(v, X, Y), var)
`

Just replace the last line by :
`var = opt.step(lambda v: cost(v, X_batch, Y_batch), var)`

**Comment by co9olguy** [comment]
Thanks for spotting the typo @chMoussa. 
@mariaschuld can you take a look at this when you have a chance?

**Comment by mariaschuld** [comment]
Thanks @chMoussa. Will push the fix asap.
