### ISSUE TITLE
Query: use of hardcoded values

### ISSUE THREAD

**Issue by mlxd** [XanaduAI/pennylane#131]
Hi, this is more of a general query, than anything else.

I noticed that in the `AdamOptimizer` class in `apply_grad` there was a hardcoded value (`1e-8`) added to the result of an operation (which I assume is to prevent values exploding in the division). Would it make more sense to use a machine epsilon value here, such as `np.finfo(float).eps` or `np.finfo(np.float32).eps`? 

I don't expect it would make much difference to any result, and removes the use of arbitrary values. If the value is chosen for a specific reason, then feel free to ignore this. Thanks!

https://github.com/XanaduAI/pennylane/blob/4aeb842f09ec3795ef9208ace13fc7c46e60d43d/pennylane/optimize/adam.py#L94

**Comment by co9olguy** [comment]
Hi @mlxd, yes that numerical value would be there to ensure that the denominator doesn't explode for small `s` values.
@mariaschuld can comment why that specific value was chosen, since she wrote that section of the code

**Comment by co9olguy** [comment]
Closed with PR #132
