### ISSUE TITLE
DisplacedSqueezedState() and issues with complex parameters

### ISSUE THREAD

**Issue by cgogolin** [XanaduAI/pennylane#146]
The documentation of [DisplacedSqueezedState](https://pennylane.readthedocs.io/en/latest/code/ops/cv.html?highlight=displacedsqueezed#pennylane.ops.cv.DisplacedSqueezedState) suggests that `DisplacedSqueezedState()` takes a complex parameter as its first value. One would this expect that the following code should work:
```
num_subsystems = 1
dev = qml.device('default.gaussian', wires=num_subsystems)
a = 0.2+0.2j
r = 0.4
phi = 0

@qml.qnode(dev)
def circuit1():
    qml.DisplacedSqueezedState(a, r, phi, wires=[0])
    return qml.expval.MeanPhoton(wires=[0])

print(circuit1())
```
but it doesn't: `TypeError: DisplacedSqueezedState: Real scalar parameter expected, got <class 'complex'>.`

Indeed, the `par_domain` of `DisplacedSqueezedState` is `R` and [there is no](https://pennylane.readthedocs.io/en/latest/API/operation.html?highlight=par_domain#pennylane.operation.Operation.par_domain) `par_domain` for complex parameters.

A similar problem will arise with `CatState`, which also claims to have a `complex` argument.

Shall we make `DisplacedSqueezedState()` take magnitude and phase of `alpha` separately, or do we want to support complex arguments via a separate `par_domain` value? If we do the latter, how do we deal with `Operations` that have some parameters from one domain and others from another?

As a further minor point: in the signature specification of  `DisplacedSqueezedState` in the docs, `alpha` is called just `a`.

**Comment by josh146** [comment]
Good catch. Since we already support magnitude and phase in most other cases (i.e. `Displacement(r, phi)`, my preference is just to do the same here, i.e.,

```python
qml.DisplacedSqueezedState(a, a_phi, r, r_phi)
```

(argument names TBD). @co9olguy, any preferences?

**Comment by co9olguy** [comment]
Agreed @josh146
