### ISSUE TITLE
Hermitian conjugate/inverse of operations

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#147]
Currently, there is no user-facing method in PennyLane of specifying the Hermitian conjugate of a quantum operation. This is perhaps not a big issue for a majority of the CV operations, and even some of the qubit operations, where we can often simply negate the gate parameter, but is useful in a few cases (one that comes to mind is the S gate).

It would be nice to provide this functionality. By building it into PennyLane core, it will then be automatically supported for any plugins that implement custom quantum operations.

Some options for the UI could include:

1. Providing a function that acts on the `Operation` class:

   ```python
   qml.dagger(qml.Gate(wires=2))
   ```

2. Providing a method/property on the `Operation` class:

   ```python
   qml.Gate(wires=2).dagger()
   ```

3. Providing a keyword argument:

   ```python
   qml.Gate(wires=2, dagger=True)
   ```

**Comment by josh146** [comment]
My personal preference is option 2. Note that this wouldn't necessarily need to _do_ anything in PennyLane core, apart from simply set an attribute on the operation so that the plugin knows to implement the Hermitian conjugate.

**Comment by cgogolin** [comment]
Option 2 seems to be the best in terms of readbility, but for simplicity I would like to suggest to make it a property, i.e, `qml.Gate(wires=2).dagger`.

For real unitaries inverse and dagger are obviously the same, but on an simulator (think Fock) they are not. Does that provide a reason in favor of either `inverse()` or `dagger()`?

**Comment by josh146** [comment]
A property looks good. My thinking was that `inverse` would be useful for custom unitaries used in `QubitUnitary`, and may result in more efficient decompositions in some frameworks as defining the inverse unitary matrix manually is avoided.

But I'm on the fence, happy to hear your thoughts on this!

**Comment by co9olguy** [comment]
I like either 2 or 3. For 2, I think a property is cleanest (like you you can do a.T in numpy)

Which is actually easiest to code up given the way we structure QNode?

**Comment by josh146** [comment]
I think option 3 is the easiest (since the `Operation` 'adds itself' to the queue, it can simply also set this value on initialization). 

But, I do prefer option 2 (as you say it's similar to a.T in NumPy), so it would be nice if this could be implemented.

**Comment by co9olguy** [comment]
This doesn't appear to be a high-priority feature at the moment. Closing, but we can reopen if the need arises in future.

**Comment by josh146** [comment]
:+1: Since creating this issue, I've decided a better short terms solution is to create a separate `S` and `Sdg` operation to be applied. This is mirrors how it is done in Qiskit (but not PyQuil or StrawberryFields).
