### ISSUE TITLE
Shape/size of qnode parameters cannot change from call to call

### ISSUE THREAD

**Issue by cgogolin** [XanaduAI/pennylane#156]
The construction of the "model" for (un)flattening is done when a qnode is fist called, because only then can the shape and size of its arguments be known. 

This however means that the following will fails:
```
@qnode(dev)
def circuit(a)
    ...
    return qml.expval.....

a = np.array([1,2,3])
circuit(a)
circuit(a[:-1])
``` 
This should be explained in the docs, the resulting error message should be improved and in the long run this should be fixed.

**Comment by josh146** [comment]
A short-term solution would be the following:

```python
a = np.array([1,2,3])
circuit(a)
a[-1] = 0
circuit(a)
```

i.e. set to zero the parameters you would like to ignore

**Comment by co9olguy** [comment]
What use-case can you imagine where we'd want to change the shape of a model/circuit's parameters like this? 
Even in regular python (ignoring any PL constructions), if you have a function that has an array argument, then indexes into those arguments, then providing it with an input of the wrong/changed shape will throw an error

```def python_function(a):
    return a[0] + a[1]
circuit(a)
cicuit(a[0:1])
```

**Comment by josh146** [comment]
@co9olguy, I tend to agree

**Comment by cgogolin** [comment]
I ran into this while writing tests for `Interferomerter()`. This now allows the last list of rotation angles to either be of length N-1 (sufficient for universality) or of length N (more symmetric circuit diagram). The parameters are obviously to be passed arguements to a qnode, but after callint that qnode once with either N or N-1 rotation angles, the other doesn't work anymore. 

I am wondering whether one could not just check the length of the flattened parameter list during circuit contstruction and then either throw a useful error message if in a subsequent call the length doesn't match, or, even re-trigger the circuit construction. Wouldn't that make sense? Or are there implementation specific complications that I overlook?
