### ISSUE TITLE
Setter to change the learning rate of optimizers on the fly

### ISSUE THREAD

**Issue by artix41** [XanaduAI/pennylane#158]
## Enhancement request
A common technique in ML, called *learning rate scheduling*, is to change the step size after a certain number of iterations. It's possible to do it with Pennylane with `op.stepsize=new_stepsize`. However, it's not very clean and having a method `op.set_stepsize(new_stepsize)` would make the code cleaner (IMO)

**Comment by co9olguy** [comment]
Thanks Arthur, this looks like an easy enhancement that we can likely sneak in before the next version release :+1:
