### ISSUE TITLE
Add PyTorch/TensorFlow/Keras custom nn modules for various QML templates

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#166]
In PennyLane v0.2, we introduced the [QML Templates](https://pennylane.readthedocs.io/en/latest/code/template.html) submodule, containing several variational quantum circuit templates, each composed of various quantum layers.

Now that we have PyTorch and TensorFlow support, it would be nice to also provide custom `torch.nn.Module`/`tf.keras.layers` that implement the same or even additional QML templates, providing a higher abstraction for working with QML and PennyLane.

**Comment by therooler** [comment]
Is this still something you would like to see implemented? I have some experience with writing custom TensorFlow layers that use PennyLane, so I would be happy to pick this up.

**Comment by josh146** [comment]
Hi @therooler, if it is something you would like to look into that would be a great contribution :) Even if it begins in the form of a tutorial or script to explore the integration between `keras`/`torch.nn` and PennyLane.

**Comment by SatyaKuppam** [comment]
@josh146 If nobody is working on this, I can pick this up.

**Comment by co9olguy** [comment]
@SatyaKuppam Cool, it would be great to see what you can code up :smile:
