### ISSUE TITLE
Add more templates and make docs user-friendly

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#167]
The CVNeuralNet template could be improved by:

- Making clear that it is not a full quantum neural net template, but just for the circuit. (Maybe rename to CVNeuralNetLayers)?
- Improve description of parameters to feed in. Currently the CVNeuralNetLayer requests 9 lists of parameters, but in practice it needs actually 11 (see test). 
- Clarify what "length N arrays of squeezing amounts " means in CVNeuralNetLayer

A major help would be a util for each template that creates a randomly sampled (uniform or Gaussian) list of parameters of the correct shape.

**Comment by mariaschuld** [comment]
\

**Comment by josh146** [comment]
@mariaschuld, could you make the recommended changes in a PR? I agree that the `CVNeuralNet` template has a very confusing docstring, and it would be a massive improvement to help clarify this.

> A major help would be a util for each template that creates a randomly sampled (uniform or Gaussian) list of parameters of the correct shape.

This is a very good idea, and I recommend a separate PR for this feature.

**Comment by co9olguy** [comment]
Docs changes done in #173

**Comment by co9olguy** [comment]
Is the "add more templates" part not still an open issue?

**Comment by josh146** [comment]
I feel this gets subsumed into #174
