### ISSUE TITLE
Convert the QNode queue to a DAG

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#169]
At the moment, the QNode creates a simple temporal queue of quantum operations/expectations to be applied to the device when executed.

In the case of CV devices, analytic gradients are currently not supported when the gate to be differentiated is succeeded at some point by a non-Gaussian quantum operation (i.e., the Kerr gate or the cubic phase gate). Thus, in the case of a temporal queue, the presence of a non-Gaussian gate _anywhere_ after the gate to be differentiated will cause a fall-back to numerical differentiation, _even if the non-Gaussian gate is applied to a different wire_.

As a result, it will actually be more advantageous to use a [directed acyclic graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (DAG) to represent the queue.

There are several TODOs and pseudocode commented in the file `qnode.py`, to guide anyone that wishes to add DAG support to the qnode.

**Comment by johannesjmeyer** [comment]
Actually, I think that using a DAG could also be advantageous for `default.qubit`. Consider the following circuit on 4 wires:
```python
def circuit(var):
   qml.PauliRX(var[0], wires=0)
   qml.PauliRX(var[1], wires=1)
   qml.PauliRX(var[2], wires=2)
   qml.PauliRX(var[3], wires=3)
   qml.PauliRY(var[4], wires=0)
   qml.PauliRY(var[5], wires=1)
   qml.PauliRY(var[6], wires=2)
   qml.PauliRY(var[7], wires=3)
   qml.CNOT(wires=[0,1])
   qml.CNOT(wires=[2,3])
   qml.PauliRX(var[8], wires=0)
   qml.PauliRX(var[9], wires=1)
   qml.PauliRX(var[10], wires=2)
   qml.PauliRX(var[11], wires=3)
   qml.PauliRY(var[12], wires=0)
   qml.PauliRY(var[13], wires=1)
   qml.PauliRY(var[14], wires=2)
   qml.PauliRY(var[15], wires=3)
   qml.CNOT(wires=[0,1])
   qml.CNOT(wires=[2,3])
```
As we always start from the 0-state, which is a product state, we could evolve the first modes all separately which means that we have way smaller matrices to multiply. After the two CNOTs, we can still evolve the pairs [0,1] and [2,3] separately until the final CNOTs where we have to use the full matrices in our calculations.

This could speed up default.qubit in certain shallow circuits and if `default.qubit` uses a DAG internally this should be easy to implement. Do you think this is worthwhile? Or do you think the overhead would diminish performance in most cases?

**Comment by josh146** [comment]
The improvements made by @co9olguy to default qubit (#239) has already replaced all large dense multiplication with a much faster `tensordot` approach, so I feel like most of the speed improvement has already been made wrt matrix multiplication.

**Comment by co9olguy** [comment]
@smite left a few pointers in code about where exactly we need to make changes to implement DAGs. 

wrt `default.qubit`, could there be some potential advantage in recognizing gates which can act synchronously (e.g., on different wires at the same time), and sending these as one combined matrix multiply (albeit a slightly larger matrix)?

**Comment by johannesjmeyer** [comment]
> @smite left a few pointers in code about where exactly we need to make changes to implement DAGs.

I've seen those, they will prove helpful I think. 
> wrt `default.qubit`, could there be some potential advantage in recognizing gates which can act synchronously (e.g., on different wires at the same time), and sending these as one combined matrix multiply (albeit a slightly larger matrix)?

I think that would probably help. But it would also mean to change the internal structure of the default.qubit plugin significantly: We then would use `apply` to collect all the operations into a DAG and use `pre_measure` to do the actual computation. If this would be implemented, we could in the future give (simulation-) plugins access to the internal DAG of the QNode.

Maybe we can implement this in default.qubit first and then lift the implementation to the QNode as a next step.
