### ISSUE TITLE
Support broadcasting single wire operations and expectations to more than one wire

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#170]
Currently, all quantum operations and expectation values in PennyLane act on a single wire; for example, if you wish to return Pauli-Z expectations for three wires, you would have to do

```python
return qml.expval.PauliZ(0), qml.expval.PauliZ(1), qml.expval.PauliZ(2)
```

It would be useful to also allow **local** (single wire) operations and expectation values to apply to more than one wire, i.e.,

```python
@qml.qnode(dev)
def circuit(x, y):
    qml.ops.Hadamard(wires=[0, 3])
    qml.ops.RX(x, wires='all')
    return qml.expval.PauliZ(wires=[0,2])
```

This should be a relatively simple modification. For example, the `QNode.construct()` method could be modified such that `qml.expval(wires=[0, 2, 5])` automatically gets translated into the tuple `qml.expval(wires=0), qml.expval(wires=2), qml.expval(wires=5)`. Similarly, when constructing the operator queue, a list of wires (or `'all'`) could be automatically 'broadcast' or expanded.

**Comment by quantshah** [comment]
Okay, I dug a little deeper into this and discussed with @josh146. It seems that trying to support broadcasting to multi-wires leads to some ambiguity which might not be desirable in the long term.

E.g., if we take `expval.PauliX(2)` vs `expval.PauliX([0, 2])`, it seems that broadcasting is convenient. But what about a two or three qubit gate? Do we do `expval.Toffoli([(1, 2, 3), (5, 6, 7) ])`.

In the spirit of PEP20 - the Zen of Python, it seems that the current method is the most optimal. One can always do a list comprehension for multiple wires in case of both single and multi-qubit gates.

```return qml.expval.PauliZ(wires = [0, 2])` vs `return [qml.expval.PauliZ(w) for w in wires]```

Or, 

```return qml.expval.Toffoli(wires = [(0, 1, 2), (3, 4, 5)])` vs `return [qml.expval.Toffoli(w) for w in wires]```

In any case, if we wish to implement this for other reasons such as parallel computation, I think we just need to change [`check_wires`](https://github.com/XanaduAI/pennylane/blob/master/pennylane/operation.py#L306) to identify such a case and then rewrite the expectation value computation in [pennylane._device](https://github.com/XanaduAI/pennylane/blob/master/pennylane/_device.py#L212). Still not sure if it is worth doing all these changes just to get single qubit broadcasting to work when the alternative - list comprehension is the more pythonic way of doing it.

**Comment by josh146** [comment]
I tend to agree, single wire gate broadcasting would simply be a convenience for the user, and not introduce any new or additional functionality. At the same time, it has the chance to cause some confusion with multi-wire gates.

Taking into account #175, which would be a significant feature addition, my current thinking is to close this issue and treat list comprehension as the preferred method for 'broadcasting' single wire operations.
