### ISSUE TITLE
Support multi-wire expectation values for qubits

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#175]
*Note: this is a separate but related issue to #170 (Support broadcasting single wire operations and expectations to more than one wire)*

A feature that would be very useful in PennyLane is the ability to return an expectation value corresponding to the tensor product of various single qubit observables; i.e., multi-wire expectation values. In the qubit case, this is a trivial change (see [this discussion post](https://discuss.pennylane.ai/t/optimizing-state-overlap-multi-qubit-qml-expval-hermitian/84)), but more care would have to taken in the CV case.

There are two ways this could be allowed:

1. Allow `qml.expval.Hermitian` to accept an arbitrary NxN Hermitian matrix, acting on N wires. Currently, it only accepts a 2x2 Hermitian matrix on a single wire.

2. Provide an interface for the user to return tensor products of existing expectation values. This could look something like this:

   ```python
   return qml.tensor(qml.expval.PauliZ(0), qml.expval.PauliX(3))
   ```
   or 
   ```python
   return qml.expval.PauliY(0), qml.tensor(qml.expval.PauliZ([0, 1]))
   ```
   after #170 is merged.

   Alternatively, we could even use operator overloading so that `+ == qml.Tensor`:

   ```python
   return qml.expval.PauliZ(0) + qml.expval.PauliX(3), qml.expval.PauliY(2)
   ```

While this is easy to support on simulator devices, I also need to think about whether this is easy to support with hardware backends.

**Comment by josh146** [comment]
After thinking about it some more, this should also be easy to support on the hardware backends, following a similar procedure as done in the rigetti/pennylane-forest package (see [here](https://pennylane-forest.readthedocs.io/en/latest/usage.html#arbitrary-hermitian-observables)).

For example, consider a 2 wire observable O:

1. Take the eigenvectors of the multi-wire observable O to get a unitary matrix U, this is the change of basis matrix
2. Apply this to the end of your original circuit on PyQuil or Qiskit
3. After you measure the probability values of |00>, |01>, |10>, and |11> (for the 2 qubit case), you can take the summation, weighted by the eigenvalues of U, to recover the multi-wire expectation value.

**Comment by quantshah** [comment]
This needs a bit of a different approach for two-qubit vs > 2-qubit gates, e.g., Toffoli.

Consider something like `pennylane.expval.Toffoli(wires=[1, 5, 6])`. Let us say that the backend plugin `default_qubit` has an `expand_multi` method which expands the operator. Now we have to be careful as the wires specified are not in order and can be anything. The same applies to any Hermitian operator if we go multiwire. I am working on a solution but maybe we can first go for two-qubit operators and then the higher ones. 

Btw, I have no idea how this would work for CV.

**Comment by josh146** [comment]
See #212 for up to date discussions
