### ISSUE TITLE
For exact analytic expectations, use shots=None

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#178]
> Would intializing `shots=None` make more sense in the case of an exact analytic expectation? This is mostly just a personal preference, but in `expval` of numpy_wavefunction.py we're dividing out by self.shots, and in such cases I like to limit towards `TypeError` rather than `ZeroDivisionError`.

_Originally posted by @msohaibalam in https://github.com/rigetti/pennylane-forest/pull/4_

I tend to agree in this case; at the expense of allowing `shots` to accept a non-numeric argument value, `shots=None` makes more sense on face-value than `shots=0`.

Thoughts on making this change?

**Comment by co9olguy** [comment]
yep, seems sensible

**Comment by josh146** [comment]
This has been superceded by #305.
