### ISSUE TITLE
scipy import bug

### ISSUE THREAD

**Issue by quantshah** [XanaduAI/pennylane#180]
#### Issue description
When calling `pennylane.ops.cv.Rotation._heisenberg_rep([phi])` if one does not explicitly import the block_diag function via `from scipy.linalg import block_diag` there is an error.

```pennylane/pennylane/ops/cv.py", line 109, in _rotation
    return sp.linalg.block_diag(1, temp) # pylint: disable=no-member
AttributeError: module 'scipy' has no attribute 'linalg'
````

This is not a bug in scipy as it is a design choice not to import top level components such as `linalg` as they are not sub-modules but directories. Read this [discussion](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/mMiv9QslB4E).

I encountered this when I wrote an independent test for the ops #99 

#### System information

* **Operating system:**
  MacOS 10.14.3 

* **PennyLane version:**
  master

* **Python version:**
Python 3.7.2 (default, Dec 29 2018, 00:00:04)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

* **NumPy and SciPy versions:**
  NumPy 1.15.0
  Scipy 1.2.1

* **Installation method:**

  Installed using  `python setup.py develop`on latest master.

**Comment by josh146** [comment]
Very good catch, this should be changed to `from scipy.linalg import block_diag` wherever it occurs.

Interestingly enough, I have noticed that some Python/SciPy installations allow this, and others do not, and I have not been able to figure out what the deciding factor is.

**Comment by quantshah** [comment]
Okay. I will try to figure out where such imports are and make a PR
