### ISSUE TITLE
pennylane-sf backend

### ISSUE THREAD

**Issue by kareem1925** [XanaduAI/pennylane#182]
hi, when I'm trying to use pennylane-sf backend on google colab i get his error

![image](https://user-images.githubusercontent.com/30449261/55670832-42715c00-5889-11e9-8485-20fa0c820d1c.png)

I tried to reset the environment but in vain 
the code was:
`!sudo pip install strawberryfields-gpu strawberryfields pennylane pennylane-sf --upgrade`

`dev_fock = qml.device('strawberryfields.fock', wires=2, cutoff_dim=10)`

I tried with and without sudo :(

**Comment by kareem1925** [comment]
it works fine on my device but not on google colab

**Comment by quantshah** [comment]
Hi, I tried to reproduce this with
```
!pip install pennylane pennylane-sf 

import pennylane
pennylane.device("strawberryfields.gaussian", wires=2)
```
and it works. Could you try this simple snippet and let me know if this works. If you have to uninstall stuff from colab you can use

```
!pip uninstall pennylane -y
!pip uninstall pennylane-sf -y
!pip uninstall strawberryfields -y
```

**Comment by kareem1925** [comment]
same error 
[notebook](https://colab.research.google.com/drive/1ZgxoApzXbzjcETL19Rhnb8dYocA_j2mi)

**Comment by josh146** [comment]
Hi @kareem1925, after you have installed PennyLane plugins, you will need to restart the Google Collab runtime in order for the newly installed devices to become available.

You can do this by clicking `Runtime` -> `Restart Runtime`, or by using `ctrl+m` on your keyboard.

As this is not a PennyLane issue, but a Google Collab issue, I am closing this issue. Feel free to ask further questions on our [discussion forum](https://discuss.pennylane.ai) or in our Slack channel.

**Comment by joeymach-ca** [comment]
Similar error! Thanks!
