### ISSUE TITLE
Implement initialization strategy for addressing barren plateaus

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#191]
#### Issue description

A strategy to circumvent the "barren plateaus" problem when training quantum circuits has been proposed here: https://arxiv.org/abs/1903.05076. It would be great to implement this as part of the templates. 

* *Expected behavior:* In the simplest case, templates have to get the option of encoding a double block strategy to allow for the "identity" trick laid out in the paper, and the parameter initialisation functions for a template get an option that uses this trick. 

* *Actual behavior:* At the moment templates do not consider this strategy

#### Additional information

This issue should best be addressed from the "add_templates" branch, which has the latest templates refactor. 

Adding it here to discuss if this is a wanted feature.

**Comment by co9olguy** [comment]
Definitely a useful feature to have, great suggestiong @mariaschuld!

Do you foresee any difficulties/issues in implementing this? How general is it? Would it work for every template?

**Comment by mariaschuld** [comment]
In theory one just needs to initialise with parameters that set a layer to the identity. That could be trivially done in the templates.utils module, whose functions return initial parameters for a template.

The paper suggest to set up every layer as a block of a circuit and its inverse, so putting in the same parameters sets the layer to the identity. That would be conceptually more difficult.

I will clarify with the authors of the paper if option 1 would be sufficient!

**Comment by josh146** [comment]
Hey @mariaschuld, what is the status of this issue?

**Comment by mariaschuld** [comment]
Haven't taken this up yet. Think it is a nice self-contained project for anyone who is interested.

**Comment by co9olguy** [comment]
We've been trying to implement this for a while (as a demo, not a feature), but can't get it to work. Have also heard from others that they had a similar experience. Closing until it becomes more clear this is possible to implement
