### ISSUE TITLE
Remove test data for loops from test_templates_layers

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#199]
Instead of having a for loop inside `test_templates_layers.py`, it is better to define the two quantum functions outside the test function, and parametrize the test data:

```python
def circuit_rect(theta, phi, varphi, wires):
    Interferometer(theta, phi, varphi, mesh='rectangular', beamsplitter='clements', wires=wires)
    return [qml.expval.MeanPhoton(w) for w in wires]

@pytest.mark.parametrize('c', [circuit_rect, circuit_tria])
def test_clements_beamsplitter_convention(self, c):
        """test the beamsplitter convention"""
        N = 2
        wires = range(N)
        dev = qml.device('default.gaussian', wires=N)

        theta = [0.321]
        phi = [0.234]
        varphi = [0.42342]

        qnode = qml.QNode(c, dev)
        assert np.allclose(qnode(theta, phi, varphi, wires), [0, 0], atol=TOL)
```

That way, if only one of them fails, pytest will show the failing case in the terminal traceback

_Originally posted by @josh146 in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjM1OTY2MTAw/pull_request_reviews/more_threads_

**Comment by co9olguy** [comment]
I believe this should be closed by latest version of template tests. If I'm incorrect, feel free to reopen
