### ISSUE TITLE
Fix the `Device.supported` method, adding a keyword argument to switch between expvals and operations, and remove the set union.

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane#205]
> We should fix the `Device.supported` method, adding a keyword argument to switch between expvals and operations, and remove the set union.

_Originally posted by @co9olguy in https://github.com/XanaduAI/pennylane/pull/203#issuecomment-494018853_

**Comment by johannesjmeyer** [comment]
The solution to this issue requested here would be something along the lines of 
```python
mydevice.supported('PauliZ', 'expectation')
```
or
```python
mydevice.supported(expectation = 'PauliZ')
```

I have to admit that I don't like either one of those solutions. If you use a keyword argument then you can easily have typos, and in the second example you are free to not give anything which is also a possible misuse.

Clearly, expectations and operations are treated as two different things here and imo they deserve a different method like
```python
mydevice.supports_expectation('PauliZ')
mydevice.supports_operation('Hadamard')
```

**Comment by johannesjmeyer** [comment]
I actually have another idea, but that would be a deeper change. What about
```python
import pennylane as qml
# [...]
mydevice.supports(qml.PauliZ)
mydevice.supports(qml.expval.PauliX)
```
This would require to add a `name` field to the `Operation` base class. Or are all the operation class names identical to their string names?

What do you think?

**Comment by josh146** [comment]
> This would require to add a name field to the Operation base class.

Currently, this is already the case: check out line 252 in `operation.py`:
```python
self.name = self.__class__.__name__   #: str: name of the operation
```
This programmatically sets the name field to the same as the operation class. However, this causes the issue where `qml.PauliZ` and `qml.expval.PauliZ` have the same name. Perhaps, instead of adding 'expectation' or 'operation' as an additional argument, the internal `device.supported` logic can be altered to take this into account?

**Comment by johannesjmeyer** [comment]
> However, this causes the issue where `qml.PauliZ` and `qml.expval.PauliZ` have the same name. Perhaps, instead of adding 'expectation' or 'operation' as an additional argument, the internal `device.supported` logic can be altered to take this into account?

This could be done in the following way, first you check `isinstance(input, Expectation)` and treat it as an expectation, then you check if it `isinstance(input, Operation)` and then act accordingly. The question is if one should allow for string input, but that would again be ambiguous.
