### ISSUE TITLE
Bug: QubitStateVector function for qubit state preparation 

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#210]
Hi,
There is some bug or inconsistency in this function. see the file jupyter notebook attached.  
```Python
dev2 = qml.device('default.qubit', wires=2)

@qml.qnode(dev2)
def make_State2(s=None):
    qml.QubitStateVector(s, wires=[0,1])
    return qml.expval.PauliZ(0),qml.expval.PauliZ(1)

state = np.array([1+0.j, 0.j, 0.j, 0-1.j])*np.sqrt(2)
print(state)
make_State2(s=state)
```
output look like this for the function call:
```Python
array([2., 2.])
```
Checking the state using
```python
dev2._state
```
gives the putput:
```python
array([1.41421356, 0.        , 0.        , 0.        ])
```

Q: Is the dev2._state function only showing the real part of the wavefunction.

Q. The expectation values are not correct. The normalization factor of the input state is throwing it off.

[test-QubitStateVector Function.pdf](https://github.com/XanaduAI/pennylane/files/3214078/test-QubitStateVector.Function.pdf)

**Comment by co9olguy** [comment]
Thanks @AroosaIjaz, definitely looks like a bug. We'll get on it and try to fix
