### ISSUE TITLE
Ensure backwards compatibility with old templates suite 

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#215]
#### Issue description

The templates restructure (see PR #195 ) has two minor feature-breaking changes:

* CVNeuralNet is replaced by CVNeuralNetLayers, which takes arguments differently
* StronglyEntanglingLayer(s) argument 'periodic' is dropped

We should make these backwards compatible. I have the changes locally, but not tested.

**Comment by josh146** [comment]
Do the feature-breaking changes lead to better usability? If so, I would argue that we have the freedom (since version number is <1) to make a breaking change without ensuring backwards compatibility.

**Comment by mariaschuld** [comment]
Yes, I'd say they do lead to more consistency and better usability of pytorch integration...

**Comment by josh146** [comment]
In which case, I would suggest it's fine to close this issue (@co9olguy?)
