### ISSUE TITLE
Bug: StronglyEntanglingLayer template 

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#225]
Hi, I am not sure if this template is working correctly. 

The following implements a one layer strongly entangling circuit  from the paper "Circuit-centric quantum classifiers" with G0=G2=H gate and G1=G3=Identity gate. 

The state at the end of the circuit is:
1/2 [ |00>|00> + |01>|11> + |10>|01>  + |11>|10> ]

The output of the expected value of PauliZ measured on subsystems qubit 0,1 and qubit 2,3 should be zero. 

```Python
n_wires = 4
pi = np.pi

dev = qml.device('default.qubit', wires = n_wires)

@qml.qnode(dev)
def circuit(angles, A=None, B=None):
    StronglyEntanglingLayer(angles, wires = range(n_wires), r=1)
    return qml.expval.Hermitian(A, wires=[0,1]),qml.expval.Hermitian(B, wires=[2,3])

pauliz = np.array([[1, 0], [0, -1]])
pauli2 = np.kron(pauliz, pauliz)
pauli4 = np.kron(pauli2, pauli2)
my_angles= np.array([[0, pi/2, 0],[0, 0, 0],[0, pi/2, 0],[0, 0, 0]])
```

```Python
circuit(my_angles, A= pauli2, B= pauli2)
```
The output is:
```Python
array([0., 1.])
```
The state  also does not look right. 
```python
dev._state
```
gives the output:
```python
array([0.5+0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j,
       0.5+0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0.5+0.j, 0.5+0.j, 0. +0.j,
       0. +0.j, 0. +0.j])
```
Am I doing something wrong or is there something going on with the template?

**Comment by josh146** [comment]
There are two recent changes that could be the cause of this bug:

1. The change to allow multi qubit expectation values #175 

2. The new template functions #195 

@mariaschuld, I'll look into the first one if you want to look into the second.

**Comment by co9olguy** [comment]
What is your expected output for `circuit` and `dev._state`?

**Comment by AroosaIjaz** [comment]
expected output for `circuit`  should be `array([0, 0])`

expected output of `dev._state` should be:
```python
array([0.5+0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j,
       0.5+0.j, 0. +0.j, 0.5 +0.j, 0. +0.j, 0.+0.j, 0.+0.j, 0. +0.j,
       0.5 +0.j, 0. +0.j])
```

**Comment by mariaschuld** [comment]
Strange: My calculations say that the script is running perfectly fine. Can you confirm @AroosaIjaz ?

Starting in |+>|0>|+>|0> (after rotations) the SEC layer does these steps

CNOT (0,1) -> (|00> + |11>) |+> |0>
CNOT (1,2) -> (|00> + |11>) |+> |0>
CNOT (2,3) -> |00> (|00> + |11>) +  |11> (|00> + |11>)
CNOT (3,0) -> |0000> + |1011> +  |1100> +  |0111>

which is the state 

``array([0.5+0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j,
       0.5+0.j, 0. +0.j, 0. +0.j, 0. +0.j, 0.5+0.j, 0.5+0.j, 0. +0.j,
       0. +0.j, 0. +0.j])``
under normal comp basis ordering (0000, 0001, 0010...)

What we expect for |psi> = |0000> + | 1011> + | 1100> + | 0011>  is <sigma^3 sigma^4> = 1/4(1+1+1+1) = 1 and   <sigma^1 sigma^2> = 1/4(1 -1 + 1 -1) = 0, so ``[0,1]`` as in PennyLane, not ``[0,0]``.

**Comment by AroosaIjaz** [comment]
Yes the function is working fine but it does not follow the formula in the paper. 

Josh and I have an idea where this confusion might be coming from:

- in the software, `imprimitive(wires=[wires[i] , wires[(i + r) % num_wires]])` where wire[i]=0,1,2,3 
- in the paper, `imprimitive(wires=[wires[(i + r) % num_wires] , wires[i]])` where wire[i]=3,2,1,0

This completely changes the state you can get at the end. I am not sure if the above circuit implemented in the software is completely entangling for r=1. The same circuit in the paper completely entangles qubit 0,1 with qubit 2,3

**Comment by mariaschuld** [comment]
Oh I see, you were talking about the paper as a comparison!

That is true, Christian wrote the function and I didn't check with the formula... But the implementation is consistent with the doc strings. My proposal would be to just say it is inspired by the paper, and the user has to then refer to the docstrings. The PL implementation is a bit simpler I feel...

**Comment by AroosaIjaz** [comment]
ok I will change the function then. 

**Also**, the documentation of `interferometer_uniform` and `interferometer_normal` is a bit confusing.  It says:

`The shape of the arrays is either (n_wires,) or (n_wires*(n_wires-1)/2,)`

The use of either/or is strange here. The output is two  arrays of `(n_wires*(n_wires-1)/2,)` and one array of (n_wires,). 

I could not understand the output when I tried to use the template just by looking at the documentation.

**Comment by co9olguy** [comment]
> 
> 
> ok I will change the function then.
> 
> **Also**, the documentation of `interferometer_uniform` and `interferometer_normal` is a bit confusing. It says:
> 
> `The shape of the arrays is either (n_wires, ) or (n_wires*(n_wires-1)/2, )`
> 
> The use of either/or is strange here. The output is two arrays of `(n_wires*(n_wires-1)/2, )` and one array of `(n_wires, )`.
> 
> I could not understand the output when I tried to use the template just by looking at the documentation.

This is a separate discussion than the `StronglyEntanglingLayer`. If you feel the docs for the interferometers can be improved, it is better discussed in a separate issue (and, even better, with a PR suggesting a fix :) )

**Comment by AroosaIjaz** [comment]
okay thanks! I will  make a separate PR for that.
