### ISSUE TITLE
Make `expval`, `measure` and `var` function abstrations

### ISSUE THREAD

**Issue by quantshah** [XanaduAI/pennylane#226]
This issue is for discussing a clean refactoring of the expectation `pennylane.expval`, single shot measurement, `pennylane.measure` and variance `pennylane.var` functions. This follows #212 where we were discussing the issue of adding a `Tensor(op1, op2)` function for tensor products. The problem is that right now, the operators and the expectation functions are tied together as `qml.expval.PauliX()`. This will lead to a lot of code duplication whenever we want to add a new functionality and also clutters the API, e.g., do we do `pennylane.expval.Tensor()` or `pennylane.expval(Tensor(PauliX(0), PauliY(1))`. The latter will not work since `PauliX` itself inside a QNode will get added to the queue.

It is beneficial to separate out the expval function as an independent funtion which can take operators and return their expectations. It should not matter what kind of operator is passed to it, so things like

- `expval(PauliX(0), PauliY(1))`
- `expval(Hadamard(0))`
- `expval(TwoQubitOperation(control=1, target=0))`
- `expval(Tensor(PauliX(0), PauliY(1)))`

should work out of the box instead of having to define `expval.Operator()` for every new operator. 

Also, @josh146 has an idea of using factory functions #204 to compute different quantities. Note that we need to make this `expval` function work with continuous variable operators too.  Somehow, we need to define our Operator class to have a flag for "qubit" or "CV", "hermitian" or "non-hermitian" and the `expval` functions behave according to which type of operator was supplied. 

Any comments? @co9olguy

**Comment by co9olguy** [comment]
A clear and worthwhile refactor. How do you foresee that CV measurements/expvals would be different from qubit?

**Comment by josh146** [comment]
I concur with @quantshah's approach.

I suggest merging the existing `qml.expval` submodule with `qml.ops` as follows:

* `ops/`

  - `qubit.py` - contains all qubit unitaries and observables
  - `cv.py` - contains all CV unitaries and observables

In addition, we would now have to define two new class attributes for each operation:

* `unitary = True`

* `observable = True` (or maybe `Hermitian = True`?)

This allows us to raise useful errors, for instance if the user tries to do `qml.expval(qml.S)` or use `qml.Hermitian` inside a circuit. It will also work for operations that are both hermitian and unitary, such as the Pauli matrices.

**Comment by quantshah** [comment]
Actually, the little knowledge I have about CV, I only know observables such as `mean photon number` or `parity` measurements which have a matrix representation so they do not seem so different from qubit operators. But what about Homodyne measurements? We need to discretize the values for such operators (x or p) and I do not know how this is implemented in SF or PL.

**Comment by co9olguy** [comment]
@quantshah how does the representation of the operators influence the planned refactor of `expval` into a separate function rather than a submodule?

We already have all the machinery in place to represent CV expectation values and evaluate them on a PennyLane plugin, so at a first glance, I don't think anything new has to be added about the nitty-gritty of how measurements are implemented, just how the library calls them?

@josh146 any thoughts?

**Comment by quantshah** [comment]
@co9olguy Thanks for the comment which makes it clearer now. We do not need to go into the details of how the expectation is computed since the plugins take care of it. I always confuse myself thinking that pennylane is a circuit simulator which calculates the expectations, but actually, the plugins do that and we just have to make the interface.

**Comment by quantshah** [comment]
Okay, so I started thinking about how this will work. I am assuming that we do not want to break `qml.expval.PauliX()` right now. Do we add a deprecation warning and slowly remove it. E.g., we somehow find a way to keep both working simultaneously by wrapping the old `expval.PauliX()` around the new `expval` by making it a class which has methods `expval.PauliX()` etc. 

Also, thanks @josh146 for the clarification. The factories will not be needed now I guess.

**Comment by josh146** [comment]
> Do we add a deprecation warning and slowly remove it

@co9olguy, feel free to chime in here, but since we are at version number < 1, we have the freedom to make breaking changes.

In this case, I would propose not keeping the old behaviour, simply to make the refactor easier and avoid code complexity (as well as design decisions that would have to be taken to allow backwards compatibility).

**Comment by co9olguy** [comment]
Yep, I think it's ok to change the interface with sufficient info given in docs. Anyway, the pattern is pretty clear to pick up, so users will probably catch on after the first time they see it

**Comment by quantshah** [comment]
@josh146 when you say the following, you still mean that there will be expval.py function which accepts any `pl.ops` such as `PauliX(Operation)` and calculates the expectation value?

> I suggest merging the existing qml.expval submodule with qml.ops as follows (to avoid needing to flag every operation as qubit/CV):
> 
> ops/
> 
> qubit.py - contains all qubit unitaries and observables
> cv.py - contains all CV unitaries and observables
> In addition, we would now have to define two new class attributes for each operation:
> 
> unitary = True
> 
> observable = True (or maybe Hermitian = True?)

I was thinking of the following code structure, and removing the `expval` submodule and replacing it with a top level `expval.py` function/class.

pennylane
    - ops
        - qubit.py
        - cv.py
    - optimize
    - __init__.py
    - operation.py
    - **expval.py**
    - **measure.py**
    - var.py
    - utils.py

Since the expectation of an operator is not related to any `ops.py` by acts on them. What do you think?

**Comment by josh146** [comment]
Yes, exactly. When I say 'merge the expval and ops modules', I mean more make sure any observables defined in `expval/qubit.py` and `expval/cv.py` but *not* in their `ops/` equivalent are moved over.

The `expval` function could be done in several ways. Here is one approach (feel free to suggest others):

* The `Expectation` class is currently very sparse; it inherits from `Operation` and adds only one extra method.

   In this approach, we move everything into the `Operation` (or `CVOperation`) class - everything becomes an `Operation`/`CVOperation`, with either/both of `unitary` and `observable` class attributes set.

* The `expval` function then accepts an `Operation` class, and, iff `observable == True` modifies it in some way, so that the receiving device knows what to return (for example, it could set a `return = 'expval'` property).

This would scale easily to additional `measure`, `var`, functions down the line.

**Comment by josh146** [comment]
You may find that the `expval`, `measure`, and `var` functions are small enough that they could all be in one file - `output.py`?

**Comment by quantshah** [comment]
I am facing some issue now with the queuing. The `expval` function could have the following signatures and only one of them could work now which needs a way for the QNode context to be available to the expval function. 

- This could work **`pl.output.expval(PauliX, wires=[0])`** but then we need to somehow pass the expval function the QNode context or the quantum function to really make it compute the value.

- This **`pl.output.expval(PauliX(wires=[0], do_queue=False))`** looks slightly easier to implement as we are just passing an operation and not queuing anything. We do not queue the operation inside the circuit but somehow do it inside the expval function. But then again we need the QNode context to do this.

- This is the best **pl.output.expval(PauliX(wires=[0]))** but then again `PauliX(wires=[0])` already queues the operation inside the circuit. If switch queuing off by default then, we will break the standard behavior of just calling an operation inside the circuit and it being queued automatically. So we need to somehow identify when an operation is executed inside the quantum function, or inside the `expval` function.

I will discuss more today with @josh146 regarding this. Please feel free to comment.

Here is a simple test case which can be run with one of the choices for the API.
```
import pennylane as pl
from pennylane.ops import PauliX
import pytest

dev = pl.device('default.qubit', wires=2)

def test_expval():
    """expval: Tests the `expval` function.
    """
    def circuit():
        pl.Hadamard(wires=0)
        return (pl.expval.PauliX(0),
                pl.output.expval(PauliX, wires=[0]),
                pl.output.expval(PauliX(wires=[0], do_queue=False)),
                pl.output.expval(PauliX(wires=[0])))
    
    qcircuit = pl.QNode(circuit, dev)

    assert qcircuit() == (0., 0., 0., 0.)
```

**Comment by co9olguy** [comment]
All previous `expval`s are now `observables`, and the `qml.expval` function was added in #232

**Comment by co9olguy** [comment]
Leaving open since we will still need to add `qml.var` and `qml.measure`

**Comment by co9olguy** [comment]
`qml.var` added in #240

**Comment by josh146** [comment]
Complete now that #256 has been added
