### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by RohitMidha23** [XanaduAI/pennylane#245]
#### Issue description

![pennylane_error](https://user-images.githubusercontent.com/38888530/60015575-76e30000-96a1-11e9-80fd-ee9b3ffb742c.PNG)

* *Expected behavior:* This is a screenshot from the [documentation](https://pennylane.readthedocs.io/en/latest/tutorials/qubit_rotation.html) and if you notice, the hyperlink for supported expectations doesn't work.

* *Actual behavior:* No hyperlink.

* *Reproduces how often:* Always, I suppose. 

#### System information

* **Operating system:**
Chrome Browser 

#### Additional information

From the recent issues I noticed that `expval` was merged and hence I suppose this is supposed to hyperlink to `measure.rst`. If that's the case, I'll change it and submit a PR accordingly.

**Comment by co9olguy** [comment]
Good catch @RohitMidha23! Indeed, the expval behaviour has just been refactored in the code. A PR to fix this would certainly be appreciated :+1:

**Comment by RohitMidha23** [comment]
@co9olguy just a suggestion, but maybe move the `CONTRIBUTING.md` to the main repo as well. Another thing would be too add a slightly more comprehensible guide with instructions on setting up the repository, etc. Just a small suggestion. If you approve I can work on that as well 😄

**Comment by RohitMidha23** [comment]
@co9olguy closing this issue now. Please do give those suggestions a look through though. Thanks 😄

**Comment by josh146** [comment]
@RohitMidha23, if you think the documentation on getting started with PennyLane development can be improved in anyway, please feel free to make a PR! We're always looking for ways to improve our documentation 🙂

**Comment by co9olguy** [comment]
Hi @RohitMidha23, we welcome any pull requests that can improve the library in some way. We are refactoring the docs at the moment (see a number of related PRs #216, #222, #235, #236, #237, #238). The goal is for these to be merged in next couple weeks, so now is exactly the right time to suggest improvements to docs :) )
