### ISSUE TITLE
Gradient recipe notation is confusing in gate docstrings

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#247]
### Issue description

Whilst making a PR on controlled rotation gates, I realized that the gradient recipe for Rx, Ry and Rz does not seem to be correct in the documentation. I do not have access to how it was coded, though.

current gradient recipe  

`\frac{d}{d\phi}R_x(\phi) = \frac{1}{2}\left[R_x(\phi+\pi/2)+R_x(\phi-\pi/2)\right]` 

right gradient recipe

`\frac{d}{d\phi}R_x(\phi) = \frac{1}{4}\left[R_x(\phi+\pi/2)-R_x(\phi-\pi/2)\right]` 

the factor should be 1/4 and the two evaluations R(phi+pi/2) and R(phi-pi/2) should subtract **not** add. this hold for all rotations; RX, RY, RZ.

![rx](https://user-images.githubusercontent.com/44415402/60127804-1d410b00-975f-11e9-9025-ee42dad732ca.JPG)
![ry](https://user-images.githubusercontent.com/44415402/60127814-2205bf00-975f-11e9-8e95-a3b9dda286f0.JPG)
![rz](https://user-images.githubusercontent.com/44415402/60127820-24681900-975f-11e9-9391-f7accc9be4c8.JPG)

**Comment by josh146** [comment]
Hi Aroosa! There is a slight subtlety to remember here, which is that when the docs refer to the gradient of gates, it means 'gradients of gates with respect to expectation values'.

So while it is written in the docs as 
![image](https://user-images.githubusercontent.com/2959003/60143930-3398a680-97f3-11e9-9a00-c79aca373be6.png)

what we are instead referring to is not the derivative of the unitary operation directly, but the derivative of the _expectation value_ with respect to parameter theta, which is parametrized by a rotation gate.

In this case, the parameter shift formula from the PennyLane docs gives the expected result:
![image](https://user-images.githubusercontent.com/2959003/60144263-4cee2280-97f4-11e9-8c50-cc562d75bab4.png)

**Comment by AroosaIjaz** [comment]
Oh. Thanks @josh146 for answering in detail! 

I will close this issue and make a PR for controlled rotation gates then :)

I do not know how to code them on the backend, however. Can you share the code from the original rotation gates (maybe on slack) ? 

Thanks

**Comment by co9olguy** [comment]
Hi @AroosaIjaz, all code is open-source, and available directly in this github repo :)

**Comment by co9olguy** [comment]
@AroosaIjaz, I can see why anyone would get confused reading those, the gradient recipe in those docstrings is misleading

**Comment by co9olguy** [comment]
We should also fix the apparent typo in the "+" sign

**Comment by josh146** [comment]
@AroosaIjaz, what docs page did you see the typo on?

**Comment by co9olguy** [comment]
I believe she was referring to here: https://pennylane.readthedocs.io/en/latest/code/ops/qubit.html

**Comment by AroosaIjaz** [comment]
> I believe she was referring to here: https://pennylane.readthedocs.io/en/latest/code/ops/qubit.html

It should be `-` on the right hand side between the two evaluations


![Screenshot from 2019-06-26 10-17-36](https://user-images.githubusercontent.com/44415402/60187546-c0476280-97fb-11e9-8b9f-7962a502f318.png)
.

**Comment by AroosaIjaz** [comment]
I can make a PR for this quickly.

**Comment by josh146** [comment]
> We'll leave this issue open as a reminder to fix up those docstrings and make it more clear that the unitary matrix is not the thing that appears in the gradient recipe, but rather the application of that gate in a circuit (i.e., the expectation value)

I agree, definitely not clear (it even confused me for a second before I remembered). One thing that makes it even more muddled is that the gradient recipe in CV _does_ apply/work with the Gaussian symplectic matrices.

**Comment by co9olguy** [comment]
I believe all the issues discussed here have now been dealt with and merged into master
