### ISSUE TITLE
Missing code snippet in docs on measurement module

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#249]
#### Issue description

in https://pennylane.readthedocs.io/en/latest/code/measure.html, it says "For example, the following QNode returns the expectation value of observable PauliZ on wire 1, and the variance of observable PauliX on wire 2."

The code snippet is not displayed, however.

![Screenshot from 2019-06-26 11-11-45](https://user-images.githubusercontent.com/44415402/60192161-6f3b6c80-9803-11e9-91f9-9a7b4e74f36b.png)

**Comment by co9olguy** [comment]
Thanks @AroosaIjaz, can you suggest a fix?

**Comment by josh146** [comment]
Hi Aroosa, it might be referring to the code snippet in the decorator.py docstring - you can copy it here as well if you think that will fix it.

**Comment by AroosaIjaz** [comment]
> Hi Aroosa, it might be referring to the code snippet in the decorator.py docstring - you can copy it here as well if you think that will fix it.

there is no code snippet that measures variance in decorator.py

**Comment by AroosaIjaz** [comment]
I checked the `measure.py` file. The code snippet is just NOT being displayed. Let me see how to fix that.

**Comment by AroosaIjaz** [comment]
we just need to specify `python` with the `.. code-block::` command.

Will make a PR for this too.

**Comment by josh146** [comment]
Good catch @AroosaIjaz!

**Comment by co9olguy** [comment]
reopening until PR is merged
