### ISSUE TITLE
RandomCircuit template rebuilds circuit every time qnode is used

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#250]
As of v0.4 of PennyLane, circuits are not cached any more, which means every time a qnode is called the quantum circuit is rebuilt from the quantum function. That means that random choices in the architecture get redone with every run.

* *Expected behavior:* A template circuit architecture is fixed for a node

* *Actual behavior:* See above

***********************
While caching could in principle done by building the qnode with cache=True argument, a template does not have access to the qnode building procedure, since it can be used in any qnode. 

Actually, I am not sure how to fix that. I could pick a seed, but where would I set the seed, if anything in the template must be fixed? In other words, how can I induce randomness in a function that in some calls must not be random?

**Comment by josh146** [comment]
Off the top of my head, I can think of maybe a couple of options (@co9olguy may have more):

1. You could have a keyword argument in the function signature that sets the seed

2. You could have the docstring specify (maybe using `.. important::`) that `cache=True` if using `RandomCircuit`. I don't personally like this approach though.

**Comment by mariaschuld** [comment]
I would also not do 2., and my concern with 1. is that usually random functions show random behaviour if a seed is not given, and deterministic one otherwise. But agreed, this would be definitely an option.

**Comment by josh146** [comment]
Alternatively, you could modify RandomCircuit to return a _function_, that is created with random parameters BUT identical each time it is called. To generate a new RandomCircuit, you must call the top level wrapper to generate a new function.

Similar to the idea of how decorators are coded/structured.

**Comment by mariaschuld** [comment]
I'm not sure I understand..something like:

def _randomcirc(...):
     <<construct random circuit, using np.random>>
    return ???

def RandomCircuit(...):
   _randomcirc(...)

**Comment by josh146** [comment]
Something like this:

```python
def RandomLayersGenerator():
    random_value = np.random.random()

    def _random_layers(weights, wires, ratio_imprim=0.3, imprimitive=CNOT, rotations=None, seed=None):
        # put random layer code
        # here, using random_value instead
        # of calls to np.random.random()

    return _random_layers
```

Then, I suppose the user would have to 'initialize' a random circuit function before using it inside the QNode. Every time the 'initialized' function is called, it will use the same random value:

```python
random_circuit1 = RandomLayersGenerator()

@qml.qnode(dev)
def circuit(weights):
    random_circuit1(weights, wires=[0, 1])
    return expval(..)
```

Not sure if it is an ugly solution or not though.
