### ISSUE TITLE
Can not create QVMDevice

### ISSUE THREAD

**Issue by JiahaoYao** [XanaduAI/pennylane#257]
I am following the notes from the introduction, [link](https://pennylane.readthedocs.io/en/latest/tutorials/pytorch_noise.html). 
```
import pennylane as qml
import torch 
from torch.autograd import Variable

dev = qml.device('forest.qvm', device='2q', noisy=True)
```

However, I encountered this problem, and do not know why?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-2cf089c8119a> in <module>
----> 1 dev = qml.device('forest.qvm', device='2q', noisy=True)

/anaconda3/envs/Q10/lib/python3.7/site-packages/pennylane/__init__.py in device(name, *args, **kwargs)
    202 
    203         # load plugin device
--> 204         return plugin_device_class(*args, **options)
    205 
    206     raise DeviceError(

TypeError: Can't instantiate abstract class QVMDevice with abstract methods observables
```
Can anyone tell me what to do or is this a bug?

**Comment by josh146** [comment]
Hi @JiahaoYao. We've recently released a new version of PennyLane. We've also updated PennyLane-Forest on GitHub, but have not yet updated the `pip` release yet.

This should be done within the coming week; for now, could you update your installed version of PennyLane, and install PennyLane-Forest from the GitHub repository:

```bash
pip install pennylane --upgrade
pip uninstall pennylane-forest
pip install git+https://github.com/rigetti/pennylane-forest.git
```

Let me know if that solves the issue for you - I'll keep this open until PennyLane forest is updated on `pip` :)

**Comment by JiahaoYao** [comment]
Thanks for quick reply~ Many thanks!
