### ISSUE TITLE
Implementation of device.expval and device.var

### ISSUE THREAD

**Issue by johannesjmeyer** [XanaduAI/pennylane#260]
While working on PR #256, which is the implementation of `device.sample`, I redid the implementation of `device.expval` and `device.var` in `default.qubit`. 

The new implementation is basically `device.sample(...).mean()` and `device.sample(...).var()` if one is not in analytic mode. What do you think of making this the default implementation in the `device` baseclass? 

Of course, there are cases when plugin developers want to override `expval` and `var` because their backend has some special functionality for those or its an analytical plugin, but if it's really just obtaining samples from a hardware device then one could reduce the work of building a plugin by already implementing the functions as above.

**Comment by co9olguy** [comment]
I believe @josh146 had some thoughts on this. Would be good to state them here for posterity

**Comment by josh146** [comment]
I've thought about this a lot, and decided that this is a Good Idea™

**Comment by josh146** [comment]
I'm closing this for now, as it is a very change that can likely be re-evaluated once #178 is implemented.
