### ISSUE TITLE
QubitUnitary does not act on all wires

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#268]
#### Issue description

Description of the issue - In the documentation, QubitUnitary operator:
1. is stated to act on `all wires` in the system. I tested it and it can act on subsytem of wires. 
2. is said to support finite difference as its gradient recipe. This can not be right as we can only input a fixed, non-differentiable matrix to this operator. So the gradient recipe should be `None`.

I am making a PR for this issue.

**Comment by co9olguy** [comment]
Thanks @AroosaIjaz
