### ISSUE TITLE
Amplitude encoding should check if features are normalized

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane#270]
See [this user report](https://discuss.pennylane.ai/t/valueerror-p-1-when-playing-with-the-numbers-of-shots/184/4) on pennylane discussion forum.

It appears that the `default.qubit` plugin code which performs approximate expectation estimation with finite shots can lead to probabilities which are invalid (greater than one). This leads to an exception when `numpy.random.binomial` is called. At the moment, it is unclear what is causing this, as the probability is generated via steps that should lead to a valid probability.

**Comment by johannesjmeyer** [comment]
I'll have a look at how the sampling is implemented, maybe I'll spot something right away.

Also note that I changed the sampling behaviour in #256, _maybe_ this will already solve this.

**Comment by co9olguy** [comment]
It seems from the user's feedback that this bug may be coming from something further upstream, but only manifests during this step because numpy checks for normalized probabilities. I don't know if merging in the changes to sampling will solve or just mask the original source of the issue :thinking:

**Comment by johannesjmeyer** [comment]
Maybe it is related to the following fact in `AmplitudeEncoding`:

`The absolute square of all elements in ``features`` has to add up to one.`

I can imagine that if that was not the case we could get problems downstream. If this is correct, then we should implement some sanity check in this or better the underlying routine.

**Comment by co9olguy** [comment]
Good find. I agree on all suggestions

**Comment by johannesjmeyer** [comment]
I am actually somewhat dissatisfied with the function `AmplitudeEncoding`. Right now it's 98% percent superfluous because it has no advantage about using `QubitStateVector` directly (only that it has a speaking name). 

We could probably beef up this function a bit -- by allowing a feature vector that has less than 2^n elements (we would then pad them with zeros) and allowing that the squares don't sum to 1 (we would then normalize the vector). What are your thoughts?

**Comment by josh146** [comment]
Rather than discuss `AmplitudeEncoding` here, best to make a new issue regarding it with a descriptive title.

**Comment by johannesjmeyer** [comment]
Okay, coming back to the error, maybe we should also have a sanity check in default.qubit that checks if the internal state is valid?

**Comment by AroosaIjaz** [comment]
> Maybe it is related to the following fact in `AmplitudeEncoding`:
> 
> `` The absolute square of all elements in ``features`` has to add up to one. ``
> 
> I can imagine that if that was not the case we could get problems downstream. If this is correct, then we should implement some sanity check in `QubitStateVector` which is directly underlying `AmplitudeEncoding`. Maybe also in both to have a more informative error message.

You are right. The test that checks if `features` used by  `AmplitudeEncoding` is normalised was missing. I added one now in the PR #275 . I dont know if this fixes the error our user has, however.
