### ISSUE TITLE
Convert QNode._op_successors parameters to observable/operation scheme

### ISSUE THREAD

**Issue by johannesjmeyer** [XanaduAI/pennylane#282]
During refactoring of test_qnode.py I stumbled about the method `_op_successors` that uses `'G'` to mark operations and `'E'` to mark observables. This should be fixed to be consistent with the new naming.

This is very minor and should be done with quickly.

**Comment by johannesjmeyer** [comment]
And we should use the opportunity to replace the string parameters with enums.

**Comment by josh146** [comment]
It's a shame there isn't a `StrEnum`, to complement the `IntEnum` (though a separate package exists for this).

Note that, while I am generally in favour of replacing internal and developer-facing magic interger/string parameters with enums, the one place I am more resistant is in user-facing functions. For example, out of the following two options:

```python
example_function(A, B, method="BFLSF")
```

```python
from xyz import Methods
example_function(A, B, method=Methods.BFLSF)
```

the latter is much cleaner, magic strings can be adequately documented in documentation, and it follows the precedence set by NumPy and SciPy.

**Comment by johannesjmeyer** [comment]
> It's a shame there isn't a `StrEnum`, to complement the `IntEnum` (though a separate package exists for this).
According to the docs, you can simply implement it as 
```python
class StrEnum(str, Enum):
    pass
```
So we can have
```python
class SuccessorType(str, Enum):
    Operation = "Operation"
    Observable = "Observable"
```

___
> Note that, while I am generally in favour of replacing internal and developer-facing magic interger/string parameters with enums, the one place I am more resistant is in user-facing functions. For example, out of the following two options:
> 
> ```python
> example_function(A, B, method="BFLSF")
> ```
> 
> ```python
> from xyz import Methods
> example_function(A, B, method=Methods.BFLSF)
> ```
> 
> the latter is much cleaner, magic strings can be adequately documented in documentation, and it follows the precedence set by NumPy and SciPy.

Totally on your page here! I think user-facing code magic strings are the way to go.

**Comment by josh146** [comment]
Nice find with the `StrEnum` definition!

**Comment by johannesjmeyer** [comment]
Should be done after #306 is merged.
