### ISSUE TITLE
Make sure all state preparation functions are compatible with all plugins

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#286]
#### Issue description

We need to make sure all functions are supported in a compatible manner on all plugins. 

For example, qubit plugins other than `default.qubit` support the state prep function `BasisState` acting on ANY number of subsystems. `default.qubit` requires it to act on ALL wires. So the documentation for the function says `wires=Any` but produces an error when we use this function with the `default.qubit` plugin.

 For `QubitstateVector` function, it is probably the other way round. 

I will explicitly check all other state prep functions from gaussian plugin too.

**Comment by josh146** [comment]
Thanks Aroosa! This is definitely something we want to double check and ensure consistency, especially where it concerns the default plugins.

Unfortunately, there may still be cases where different frameworks have different restrictions, for example Qiskit vs. PyQuil. In cases like this, we should probably pick the most permissive value of `num_wires`, and any plugin that is more restrictive should then raise it's own error.

**Comment by josh146** [comment]
Operations we should double check:

- [ ] `BasisState`- ?

- [ ] `QubitStateVector` - `default.qubit` should be modified to allow state initialization on subsets of wires

- [ ] `QubitUnitary` - currently, `default.qubit` and Forest support arbitrary unitaries, Qiskit only suports single-qubit unitaries

**Comment by AroosaIjaz** [comment]
> Unfortunately, there may still be cases where different frameworks have different restrictions, for example Qiskit vs. PyQuil. In cases like this, we should probably pick the most permissive value of `num_wires`, and any plugin that is more restrictive should then raise its own error.

We should explicitly mention this restriction somewhere. Maybe as a `Note` in the documentation. The plugin documentation only mention the added operations on top of pennylane operations so the pennylane documentation has to be complete. What do you think?

**Comment by josh146** [comment]
My thinking is that the best place is the plugin readme. Every plugin should list the operations they support, as well as any changes/restrictions.

It will be too difficult to try and keep the PL documentation up to date with the rate the plugins are changing.

**Comment by AroosaIjaz** [comment]
oh! that is a better suggestion :)

**Comment by josh146** [comment]
Easier to update the readme if the plugin code ever changes as well, since they're in the same repo :)

**Comment by AroosaIjaz** [comment]
@josh146 I have asked Angus to work on this issue as I have been a bit busy with the other project :)

**Comment by angusjlowe** [comment]
Alright so after checking the behaviour of these functions on most of the plugins, I am thinking of proceeding as follows: 

1. Currently, qubit `BasisState` docstring says `num_wires=All`, but the actual operation has attribute `num_wires=Any`. Most plugins, besides default qubit, allow `BasisState` preparation on subsets of qubits. 

      - suggestion: Change qubit operations docstring to reflect `num_wires=Any`, and change default qubit plugin to support `BasisState` acting on subsets of wires. Any other plugins which don't support acting on subsets should raise their own error. 

2. Currently, `QubitStateVector` operation has `num_wires=All`, even though some plugins support state vector preparation on subsets of qubits. 
 
    - suggestion: Change `num_wires` to `Any` along with accompanying docstring and modify default qubit behaviour to support `QubitStateVector` acting on subsets of wires. Any other plugins which don't support acting on subsets should raise their own error.

3. From what I can tell, Qiskit works fine with unitaries acting on multiple wires. A tangential issue is that in theory, it should not! 

   - suggestion: Open new issue to investigate weird Qiskit `QubitUnitary` behaviour.

4. None of the plugin readmes list the supported operations 

    - suggestion: Track a new issue on common Trello backlog to update each of the plugin readmes with a list of available operations along with the number of wires they act on

If anyone has other suggestions feel free to weigh in.

**Comment by josh146** [comment]
This looks great, thanks Angus! I agree with all your suggestions.

**Comment by angusjlowe** [comment]
`BasisState` on other plugins can only be applied as a first operation - is this what we'd want default qubit to do as well?

**Comment by angusjlowe** [comment]
Update: I am making the default qubit `BasisState` replicate the first operation restriction from other plugins, and making the default qubit `QubitStateVector`obey this rule as well, despite other plugins being more flexible.
