### ISSUE TITLE
Recheck the gradient recipes of CV state-preparation functions 

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#287]
#### Issue description

The gradient methods for all CV state-preparation functions are set to `F`.  

* *Expected behavior:*
The gradient method should be `None`. A state preparation method does not depend on any parameters in principle. What do you guys think?

**Comment by co9olguy** [comment]
Definitely worthwhile to check all these. For discussion purposes, can you remind what are the meanings of the different enumerations?
e.g., `F` means "use finite-difference" and `None` means "not differentiable", correct?

**Comment by AroosaIjaz** [comment]
> Definitely worthwhile to check all these. For discussion purposes, can you remind what are the meanings of the different enumerations?
> e.g., `F` means "use finite-difference" and `None` means "not differentiable", correct?

Yes.

**Comment by smite** [comment]
Is this issue still current? The CV state preparations do depend on parameters, and I think all but `FockState` (which has `grad_method = None`)   actually are differentiable using the finite difference method, right?

**Comment by AroosaIjaz** [comment]
@smite, yes. I did not get time to test every function separately though in order to confirm this. If you have some time, you can go ahead and test this :) we can then update the docs. Thanks

**Comment by co9olguy** [comment]
I think @smite is right here. If the state preps depend on continuous parameters, the finite-difference rule applies for estimating gradients.
