### ISSUE TITLE
Change default value of the 'parameters' argument in Device.execute()

### ISSUE THREAD

**Issue by antalszava** [XanaduAI/pennylane#294]
The 'parameters' argument for the Device.execute() method has an empty dictionary as a default value which is mutable in nature.

A mutable as a default value in a method can lead to errors and unwanted behaviour hence is not a good practice.

The following is an example of how the test suite might be affected by a change (in this case the default value was simply removed):
```
TypeError: execute() missing 1 required positional argument: 'parameters'
Traceback (most recent call last):
  File "/pennylane/tests/test_device.py", line 338, in test_obs_queue_is_filled_during_execution
    mock_device_with_paulis_and_methods.execute(queue, observables)
TypeError: execute() missing 1 required positional argument: 'parameters'
```

**Comment by josh146** [comment]
Ah, good find, @antalszava!

We previously had discussion over this here: https://github.com/XanaduAI/pennylane/pull/283#discussion_r309700735

Something to note is that this keyword argument is never modified, instead we use `dict.update()` to safely copy its contents into a new dictionary:
https://github.com/XanaduAI/pennylane/blob/1788fc4831a50570589c5fc6ccfffee1a41ec0ca/pennylane/_device.py#L209

This was deliberate, and to avoid the issue you describe above.

We have several options:

1. Simply keep the code as is, and add a comment explaining _why_ we use a default value of `{}`, as well as specifying `pylint: disable=dangerous-default-value`.

2. Update it to `parameters=None` default value, and within the method have a line `parameters = parameters or {}`

**Comment by co9olguy** [comment]
Do we have a good reason why the default is `{}`?

**Comment by josh146** [comment]
> Do we have a good reason why the default is {}?

The only reason I can think of is readability.

**Comment by co9olguy** [comment]
Then I see no reason to not implement option 2

**Comment by josh146** [comment]
Closing this, as Device is now deprecated in favour of QubitDevice
