### ISSUE TITLE
Missing docstring for function `sample`  

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#304]
#### Issue description

There is no docstring or explanation of the function `sample` in the measurement module:

https://pennylane.readthedocs.io/en/latest/code/measure.html

**Comment by mariaschuld** [comment]
Thanks, I'm on it in the user docs refactor!

**Comment by mariaschuld** [comment]
@co9olguy, the expval inconsistency is due to the fact that it is a Factory, not a function...

**Comment by mariaschuld** [comment]
Yes, just importing them via a general :members: directive (not explicit :members: expval,...) does the job. Let me do a quick pull request to fix this one.

**Comment by mariaschuld** [comment]
It turns out, making expval consistent with a function docstring is more complicated since it is a ExpvalFactory object. Will open a separate issue and discuss with @johannesjmeyer. 

The missing sample docstring is fixed in PR#307.
