### ISSUE TITLE
Use `dev.shots` to modify the number of returned samples from a QNode

### ISSUE THREAD

**Issue by johannesjmeyer** [XanaduAI/pennylane#305]
While working on the Cirq plugin I also implemented the sample function. This was not as straightforward as it should be due to the variable number of samples (I know I came up with this, but right now I'm not so sure anymore): I ended up looping over all given observables and collecting the maximum number of samples requested and if it exceeded the number of shots given for the device I let the device run with that number of shots instead the one given at construction time. For the calculation of expvals and variances I still truncated to the number of shots given at construction time.

This feels kind of hacky and also has the feeling that it is code that in principal every plugin would have to implement, so it should not be in the plugins at all.

I would at the point where we are much prefer to just take `device.shots` as the number of samples. There is only one issue with that: In `default.qubit`, we use `shots=0` to indicate that we are running in analytic mode, but we still want to sample from it. 

I would propose the following changes:
* Introduce a new boolean parameter `analytic=True` in default.qubit that tells the plugin to run in analytic mode
* Force `shots > 0` because now `shots=0` makes no sense anymore
* Remove the parameter `n` from `sample` and always return `device.shots` many samples

I think this makes more sense than the current state of affairs.

**Comment by johannesjmeyer** [comment]
This would also supersede issue #178

**Comment by josh146** [comment]
> Introduce a new boolean parameter `analytic=True` in `default.qubit` that tells the plugin to run in analytic mode

thumb

> Force shots > 0 because now shots=0 makes no sense anymore

thumb

> Remove the parameter n from sample and always return device.shots many samples

thumb

I've never really seen the use case for specifying `n` in the `samples` function. It goes against the device abstraction, and adds significant complexity to the code.

**Comment by co9olguy** [comment]
DIsagree about not allowing a user to specify the number of samples. I've mentioned before the use case of wanting to compare performance of the same circuit/model/optimizer with different sample numbers. It makes much more sense to just swap out a single argument in `sample` than to instantiate an entirely new device

**Comment by josh146** [comment]
I agree that's a very valid use case.  But instead of just swapping out a single argument in `sample`, the user can instead just swap out a single argument in `qml.device`? They won't need to instantiate a new device, in the same way they won't be creating a new QNode.

In terms of the abstraction and the code base, it ends up working a lot better, and avoids the ambiguity of a user requesting QNodes with different shots per `sample` call.

**Comment by johannesjmeyer** [comment]
I think if you would want to compare performance of different numbers of shots I would do something like this:
```python
dev = qml.device("default.qubit", wires=1, shots=max_shots)
...
sample = circuit()
for n in range(max_shots):
    expval = sample[:n+1].mean()
    var = sample[:n+1].var()
    # plot to compare
```
So, just sample once, but a lot and then use only subsets to see when your statistics get good.

If we remove the number of shots as an argument from `device.sample` we can also just do this:
```python
dev =  qml.device("default.qubit", wires=1, shots=1)

@qml.qnode(dev)
def circuit():
    ...
    return qml.sample(qml.PauliX(0))

for shots in range(1, 100):
    dev.shots = shots
    sample = circuit()
```

**Comment by josh146** [comment]
I like the suggested approach, but I would use a setter rather than an attribute:

```python
for shots in range(1, 100):
    dev.set_shots(shots)
    sample = circuit()
```

**Comment by johannesjmeyer** [comment]
> I like the suggested approach, but I would use a setter rather than an attribute:
> 
> ```python
> for shots in range(1, 100):
>     dev.set_shots(shots)
>     sample = circuit()
> ```

Very good, let's do it like that then.
