### ISSUE TITLE
Make docstring for expval consistent with other functions in pennylane.measure

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#308]
#### Issue description

Since the expval measurement outcome is coded as a factory, the docstring is rendered inconsistently to other measurements such as `var`:

![Screenshot from 2019-08-29 08-49-20](https://user-images.githubusercontent.com/23052011/63917043-f5f60b00-ca39-11e9-976d-394065966e0a.png)

It would be great to hide this complexity from the user, for example by wrapping expval by a function of the signature `expval(ops)`.

**Comment by josh146** [comment]
The only reason `expval()` is coded as a class factory is to support both the new `qml.expval()` interface and deprecated `qml.expval.Obs` interface.

The best solution here is to fully deprecate the `qml.expval.Obs` interface, and convert it into a simple function similar to `sample` and `var`.

Any objections to removing the factory for the 0.5.0 release? Alternatively, any arguments for _keeping_ `qml.expval.Obs` for 0.5.0?

**Comment by AroosaIjaz** [comment]
I agree to fully eliminating `qml.expval.obs`.

**Comment by mariaschuld** [comment]
Me too, but can we catch people using  the old way with an exception?

**Comment by josh146** [comment]
Not a custom one, they will get a standard `AttributeError: name does not exist` exception from Python though

**Comment by co9olguy** [comment]
No objections

**Comment by smite** [comment]
Fixed in PR #267 (probably) by removing the deprecated interface, certainly by version 0.6.0.
