### ISSUE TITLE
Missing plot lines in VQE tutorial 

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#324]
#### Issue description

The second and third plots in the VQE tutorial do not show the plot line of the gradient descent. The legends are shown, however. 

Is this problem coming from making this file a "run" file? 

https://pennylane.readthedocs.io/en/latest/tutorials/pennylane_run_variational_quantum_eigensolver.html#vqe

* *Expected behavior:*

The plots should show the gradient descent on top of the optimization landscape.

**Comment by josh146** [comment]
@AroosaIjaz, does the example produce the correct plot when run manually? i.e.,
```console
python examples/pennylane_run_variational_quantum_eigensolver.py
```

**Comment by mariaschuld** [comment]
Yes the bug is also in the .py file...The line is somehow obscured by the contour plot. When you add a much larger offset to the z-values you suddenly see the lines.
