### ISSUE TITLE
Device 'Shots=0' argument breaks down for the SF plugin

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#334]
#### Issue description

The SF plugin has not been updated with PL Device reconfiguration where the user is not explicitly required to give 'shots=0' argument anymore. This produces the following bug when running files that use SF plugin:

```pennylane._device.DeviceError: The specified number of shots needs to be at least 1. Got 0.```

**Comment by co9olguy** [comment]
Seems to be better to track this issue in `pennylane-sf`. Can you post this issue there?

Is the issue happening with latest `pip` release of PL? or with github master branch?

**Comment by josh146** [comment]
Yes, please post this in https://github.com/XanaduAI/pennylane-sf/issues :)
