### ISSUE TITLE
Clarify the distinction between Operation.parameters and Operation.params

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#349]
In the `Operation` class, `.params` is used for the unevaluated parameters (so could contain Variable instances), while `.parameters` are evaluated.

The QNode always queries `Operation.params`, while the device always queries `Operation.parameters`.

A good solution would be to rename `Operation.params` to make it clear that these are potentially _unevaluated_ parameters.

**Comment by johannesjmeyer** [comment]
What do you think about removing `Operation.parameters` entirely? I think this is super confusing. And from an encapsulation point of view, the VariableRef instances themselves should hold the current value, shouldn't they?

**Comment by josh146** [comment]
`Operation.parameters` is currently used in a lot of places, from plugin devices, to utilities, to tests. It encapsulates the flattening/indexing/unflattening required for operations that take arrays as arguments. On the other hand, `Operation.params` is barely used (at all) outside of the operation.

Perhaps we just make `Operation.params` a private attribute?

**Comment by co9olguy** [comment]
Simplest step is to just rename it to avoid confusion, second would be to make it private

**Comment by johannesjmeyer** [comment]
I propose to rename it to `Operation._raw_parameters`. Other ideas? Should we keep `params` for now and put a DepreceationWarning?

**Comment by co9olguy** [comment]
I don't even think a deprecation warning is needed, since it's only really developer-facing

**Comment by co9olguy** [comment]
maybe `Operation.data` to indicate that it is raw numerical values?

**Comment by yishairasowsky** [comment]
i would like to try to do this, unless someone has already tackled it.

**Comment by yishairasowsky** [comment]
i made a push just now, in  minute i will make the pull reuqest

**Comment by thisac** [comment]
[ch305]

**Comment by co9olguy** [comment]
:champagne:
