### ISSUE TITLE
np.asscalar(a) is deprecated since NumPy v1.16

### ISSUE THREAD

**Issue by johannesjmeyer** [XanaduAI/pennylane#389]
Running the test suite spits out an enormous number of warnings due to `np.asscalar(a)` being depreceated. It should be replaced with `a.item()` in current numpy versions.

**Comment by johannesjmeyer** [comment]
Note  that this change is also backwards-compatible (I backtracked it to at least numpy 1.10)

**Comment by co9olguy** [comment]
Is this warning caused by pennylane itself, or one of the dependencies?

**Comment by johannesjmeyer** [comment]
Thanks for pointing this out. This was actually caused by pytest itself in `pytest.approx`. Was fixed by me simply updating pytest.
