### ISSUE TITLE
`qml.about()` function broken with latest `pip` update

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#393]
The latest version of pip, 19.3, contains a significant refactor, and as a result the `pip._internal.main` function has been moved/removed(?). This causes the following line in `pennylane.about()` to fail:
```python
_internal.main(["show", "pennylane"])
```
Currently, this can be solved by downgrading to pip v19.2, but it would be nice to fix this in a way that is compatible with both versions of pip.

**Comment by tobeyOguney** [comment]
Hi josh146!
The `pip._internal.main` function was moved in pip 19.3, and is now `pip._internal.main.main`.
