### ISSUE TITLE
Add function decomposing Hamiltonian to Pauli observables

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane#527]
We should add a function that allows users to easily decompose their Hamiltonian into Pauli operators. This is implemented in the following function:

```python
from functools import reduce
from itertools import product
from operator import matmul

import numpy as np
import pennylane as qml


def decompose_hamiltonian(H):
    N = int(np.log2(len(H)))
    paulis = [qml.Identity, qml.PauliX, qml.PauliY, qml.PauliZ]

    obs = []
    coeffs = []

    for term in product(paulis, repeat=N):
        matrices = [i._matrix() for i in term]
        coeff = np.trace(reduce(np.kron, matrices) @ H) / (2**N)

        if not np.allclose(coeff, 0):
            coeffs.append(coeff)

            if not all(t is qml.Identity for t in term):
                obs.append(reduce(matmul, [t(i) for i, t in enumerate(term) if t is not qml.Identity]))
            else:
                obs.append(reduce(matmul, [t(i) for i, t in enumerate(term)]))

    return coeffs, obs
```

**Comment by josh146** [comment]
At the moment, this function should likely go in `pennylane/utils.py`, with the tests in `tests/test_utils.py`.

**Comment by rahul1704** [comment]
Hey Josh,
I was reading the code and I have a small doubt about the second if condition. When only 1 matrix is identity the 'obs' variable is appended by the respective Pauli matrix,  but would this not create a dimension mismatch?
The appended PauliX would be (let's say for N=2) would be (2,2) but the Identity*Identity would be (4,4).
Am I missing something?

**Comment by josh146** [comment]
Hi @rahul1704! There is no dimension mismatch, because what we're doing is converting from a numeric/matrix representation to a _symbolic_ representation, using PennyLane observables. Since the output is symbolic, PennyLane has internal logic for interpreting the observable list.

For example, consider the following output, to be measured on a circuit with 3 wires:

```python
obs_list = [qml.PauliX(0), qml.PauliY(0) @ qml.PauliZ(2), qml.Identity(2)]
```

PennyLane can correctly interpret this observable list, since it knows that the quantum circuit has 4 wires. So identities are implicitly placed where needed:
```python
obs_list = [
    qml.PauliX(0) @ qml.Identity(1) @ qml.Identity(2),
    qml.PauliY(0) @ qml.Identity(1) @ qml.PauliZ(2),
    qml.Identity(0) @ qml.Identity(1) @ qml.Identity(2),
]

This is equivalent to the observable list above.

The reason why we have this if statement, instead of simply explicitly adding all identity matrices? There is a cost associated with each term in the tensor product --- the fewer terms in the tensor product (e.g., by dropping identities where not needed), the less processing overhead required :)

**Comment by rahul1704** [comment]
I figured that it was being done to save time, but the mismatch was confusing me. Thanks for your reply @josh146.
