### ISSUE TITLE
OSError: variational_classifier/data/parity.txt not found.

### ISSUE THREAD

**Issue by anonym0305** [XanaduAI/pennylane#536]
#### Before posting an issue

Search existing GitHub issues to make sure the issue does not already exist:
https://github.com/xanaduai/pennylane/issues

If posting a PennyLane issue, delete everything above the dashed line, and fill
in the template.

If making a feature request, delete the following template and describe, in detail,
the feature and why it is needed.

For general technical details check out our documentation:
https://pennylane.readthedocs.io

-------------------------------------------------------------------------------------------------------------

#### Issue description

Hi: I'm getting the following error
variational_classifier/data/parity.txt not found.
Pls see below. Thanks. 

Optimization
~~~~~~~~~~~~

Let’s now load and preprocess some data.



data = np.loadtxt("variational_classifier/data/parity.txt")
X = data[:, :-1]
Y = data[:, -1]
Y = Y * 2 - np.ones(len(Y))  # shift label from {0, 1} to {-1, 1}

for i in range(5):
    print("X = {}, Y = {: d}".format(X[i], int(Y[i])))

print("...")

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-11-4b0be71eab6a> in <module>
----> 1 data = np.loadtxt("variational_classifier/data/parity.txt")
      2 X = data[:, :-1]
      3 Y = data[:, -1]
      4 Y = Y * 2 - np.ones(len(Y))  # shift label from {0, 1} to {-1, 1}
      5 

/srv/conda/envs/notebook/lib/python3.7/site-packages/autograd/tracer.py in f_wrapped(*args, **kwargs)
     46             return new_box(ans, trace, node)
     47         else:
---> 48             return f_raw(*args, **kwargs)
     49     f_wrapped.fun = f_raw
     50     f_wrapped._is_autograd_primitive = True

/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)
    979             fname = os_fspath(fname)
    980         if _is_string_like(fname):
--> 981             fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
    982             fencoding = getattr(fh, 'encoding', 'latin1')
    983             fh = iter(fh)

/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/_datasource.py in open(path, mode, destpath, encoding, newline)
    267 
    268     ds = DataSource(destpath)
--> 269     return ds.open(path, mode, encoding=encoding, newline=newline)
    270 
    271 

/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/_datasource.py in open(self, path, mode, encoding, newline)
    621                                       encoding=encoding, newline=newline)
    622         else:
--> 623             raise IOError("%s not found." % path)
    624 
    625 

OSError: variational_classifier/data/parity.txt not found.

**Comment by co9olguy** [comment]
Hi @anonym0305,

Thanks for reporting this. The data you're looking for can be downloaded from [here](https://github.com/XanaduAI/qml/blob/master/demonstrations/variational_classifier/data/parity.txt). Once downloaded, you should the `np.loadtxt()` line it to load from the location you have placed the file on your local computer (putting it in the same folder that you execute the script from is a good bet)

I have made a separate note of this issue at https://github.com/XanaduAI/qml/issues/60, where these scripts are housed. Since the progress on improving this will be tracked there, I will close this issue here. If you still have any questions, feel free to let us know!
