### ISSUE TITLE
ValueError: could not convert string to float: '<!DOCTYPE'

### ISSUE THREAD

**Issue by anonym0305** [XanaduAI/pennylane#537]
Hi Nathan: I've followed your instructions. 

"Once downloaded, you should the np.loadtxt() line it to load from the location you have placed the file on your local computer (putting it in the same folder that you execute the script from is a good bet)," but am still getting an error **(ValueError: could not convert string to float: '<!DOCTYPE')**. 

I downloaded the file to my Github account and executed the script as below. What am I doing wrong ?

#### Issue description

ValueError                                Traceback (most recent call last)
<ipython-input-11-d60ef3548663> in <module>
----> 1 data = np.loadtxt("https://github.com/.../.../blob/master/parity.txt")
      2 X = data[:, :-1]
      3 Y = data[:, -1]
      4 Y = Y * 2 - np.ones(len(Y))  # shift label from {0, 1} to {-1, 1}
      5 

/srv/conda/envs/notebook/lib/python3.7/site-packages/autograd/tracer.py in f_wrapped(*args, **kwargs)
     46             return new_box(ans, trace, node)
     47         else:
---> 48             return f_raw(*args, **kwargs)
     49     f_wrapped.fun = f_raw
     50     f_wrapped._is_autograd_primitive = True

/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)
   1157         # converting the data
   1158         X = None
-> 1159         for x in read_data(_loadtxt_chunksize):
   1160             if X is None:
   1161                 X = np.array(x, dtype)

/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/npyio.py in read_data(chunk_size)
   1085 
   1086             # Convert each value according to its column and store
-> 1087             items = [conv(val) for (conv, val) in zip(converters, vals)]
   1088 
   1089             # Then pack it according to the dtype's nesting

/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/npyio.py in <listcomp>(.0)
   1085 
   1086             # Convert each value according to its column and store
-> 1087             items = [conv(val) for (conv, val) in zip(converters, vals)]
   1088 
   1089             # Then pack it according to the dtype's nesting

/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/npyio.py in floatconv(x)
    792         if '0x' in x:
    793             return float.fromhex(x)
--> 794         return float(x)
    795 
    796     typ = dtype.type

ValueError: could not convert string to float: '<!DOCTYPE'

**Comment by co9olguy** [comment]
Hi @anonym0305,

It looks like you put the URL (the website address) for the data into `np.loadtxt()`. You'll need to put in here instead the location you have placed the file on your local computer (e.g., if you've placed it in the same folder where you're running this python script from, you can just put `np.loadtxt("parity.txt")` (assuming you haven't changed the file name)

**Comment by anonym0305** [comment]
I'm running the script through https://nbviewer.jupyter.org/using the github weblink for the ipynb file https://github.com/.../.../blob/master/tutorial_variational_classifier.ipynb 

Shouldn't the parity.txt file also be on my github account ?

**Comment by anonym0305** [comment]
works. thanks.
