### ISSUE TITLE
qubit hamiltonian creation

### ISSUE THREAD

**Issue by Chapa1** [XanaduAI/pennylane#553]
Hello,
I have a question concerning 'qml.Hamiltonian' implementation.
When I try to create hamiltonian using 'H=qml.Hamiltonian(coeffs, obs)', I have an error 'AttributeError: 'Hamiltonian' object has no attribute 'name''. 

Here is the snippet reproducing the error:

```python
dev = qml.device('default.qubit', wires=3)
coeffs = np.array([0.2, 0.9, 0.3])
 
obs= [qml.PauliX(0) @ qml.PauliZ(1) @ qml.PauliX(2),
qml.PauliX(0) @ qml.PauliX(2),
qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2)]

H=qml.Hamiltonian(coeffs, obs)
@qml.qnode(dev)
def circuit(params):
    qml.CNOT(wires=[0, 2])
    qml.RY(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.RY(params[2], wires=2)

    return qml.expval(H)

params=[0.2,0.2, 0.2]
print(circuit(params))
```

If I replace by 'return qml.expval(obs[0])' within the function "circuit", it is working. 
However, for example 'return 0.2*qml.expval(obs[0])' gives an error.

Thank you in advance.

PS. I do not actually know it is a bug or not. I suppose that I do not use Pennylane properly .

**Comment by josh146** [comment]
Hi @Chapa1! Thanks for reporting this --- using the PennyLane `qml.Hamiltonian` object is not currently supported within QNodes; however this is something we will look into supporting.

In the meantime, what you can do is create a collection of QNodes, each one corresponding to an observable in your `obs` list, and then perform the dot product with the coefficients:

```python
dev = qml.device('default.qubit', wires=3)
coeffs = np.array([0.2, 0.9, 0.3])
 
obs = [qml.PauliX(0) @ qml.PauliZ(1) @ qml.PauliX(2),
qml.PauliX(0) @ qml.PauliX(2),
qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2)]

def ansatz(params, **kwargs):
    qml.CNOT(wires=[0, 2])
    qml.RY(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.RY(params[2], wires=2)

qnodes = qml.map(ansatz, obs, dev)
result = qml.dot(coeffs, qnodes)

params=[0.2,0.2, 0.2]
print(result(params))
```

This method has a few advantages; since we are creating 3 qnodes, one for each observable,
```python
>>> len(qnodes)
3
>>> qnodes[0](params)
0.03868274073289092
```
we have the ability to distributed them across three QPUs at the same time (if available).

Note: feel free to check out our [discussion forum](https://discuss.pennylane.ai) for any additional PL questions!

**Comment by Chapa1** [comment]
I have another issue about VQE.

Here I create curcuit 

```python
dev = qml.device('default.qubit', wires=3)
coeffs = np.array([0.2, 0.9, 0.3])
 
obs = [qml.PauliX(0) @ qml.PauliZ(1) @ qml.PauliX(2),
qml.PauliX(0) @ qml.Identity(1) @ qml.PauliX(2),
qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2)]

def ansatz(params, **kwargs):
    qml.CNOT(wires=[0, 2])
    qml.RY(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.RY(params[2], wires=2)

def circuit(params):    
    qnodes = qml.map(ansatz, obs, dev)
    result = qml.dot(coeffs, qnodes)
    return result(params)
```
 and implement optimization procedure

```python
opt = qml.GradientDescentOptimizer(stepsize=0.5)

params=[1.,0.01, 2.]
for i in range(50):
    params = opt.step(circuit, params)
    
    if (i + 1) % 5 == 0:
        print(circuit(params))
    
print('parameters=',params)
print('expectation=', circuit(params))
```
the result is -1.099 instead of an exact -1.4 
```python
H_matrix=coeffs[0]*obs[0].matrix+ coeffs[1]*obs[1].matrix+coeffs[2]*obs[2].matrix
np.linalg.eigvals(H_matrix)
```
gives [ 1.4, -0.8,  0.4, -1. ,  0.8, -1.4,  1. , -0.4]

I tried various circuits and initial parameters, but the result is the same.  I didnt manage to use 

> https://pennylane.readthedocs.io/en/stable/code/api/pennylane.VQECost.html?highlight=vqecost#pennylane.VQECost

**Comment by josh146** [comment]
Hi @Chapa1, closing this issue for now, as it is not so much a bug rather than the `qml.Hamiltonian` class cannot be used in QNodes. Let me know if you have any further questions!

**Comment by Chapa1** [comment]
Dear developers,

I have a similar question about creating Hamiltonian but for CV variables.
Is it possible using Pennylane (or StrawberryFields) to construct
CV-observables `Obs1=a n_0 n_1+b n_1n_2` and `Obs2=a q_0 q_1+b p_0p_1` where `n_0, q_0, p_0` are number, position and momentum operators for mode-0 and a,b are constants? If yes, could you please send me an example?

Thank you!
I managed to create only `a n_0+b n_1` term (see snippet). 
`qml.NumberOperator(0,1)` and `qml.NumberOperator(0)@qml.NumberOperator(0)`  not working
```
def quantum_function(params, wires, **kwargs):
    qml.FockState(3, wires=0)
    qml.FockState(2, wires=1)
    
obs_list = [qml.NumberOperator(0), qml.NumberOperator(1)]

dev_fock = qml.device('strawberryfields.fock', wires=2, cutoff_dim=10)

qnodes = qml.map(quantum_function, obs_list, dev_fock, measure="expval")
coeffs=np.array([2.,1.])
qml.dot(coeffs, qnodes)(1.0)
```

**Comment by josh146** [comment]
Hi @Chapa1, while tensor products of CV observables is not currently available, this is a feature we are working on now!

**Comment by Chapa1** [comment]
Hello @josh146,  When approximately this feature be available? In this case could you please inform me about it. Thank you!
