### ISSUE TITLE
Cache note/warning in RandomLayers

### ISSUE THREAD

**Issue by trbromley** [XanaduAI/pennylane#580]
The [RandomLayers](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.templates.layers.RandomLayers.html) documentation page has a note and a warning: 
![image](https://user-images.githubusercontent.com/49409390/78779293-b77ae400-796a-11ea-87b7-8be874a2a487.png)
However, the `cache` option for a QNode seems to have been removed in v0.8, so these boxes do not make sense anymore.

It would also be good to check if the removal of the `cache` option changes the behaviour of the random layers.

**Comment by josh146** [comment]
@mariaschuld @trbromley: this option remains, it just changed name. `cache=False` (default value) just became `mutable=True` (default value).

**Comment by mariaschuld** [comment]
I'm making a PR where I also add a test. It's bad that there was none catching this!

**Comment by mariaschuld** [comment]
In the long run it would be more user-friendly to have as default behaviour that every call to a qnode (mutable or not) uses the same random circuit...on our radar!

**Comment by trbromley** [comment]
Thanks @josh146 @mariaschuld!
