### ISSUE TITLE
default.qubit throwing exception on Google Colab

### ISSUE THREAD

**Issue by doperamine** [XanaduAI/pennylane#582]
![bug](https://user-images.githubusercontent.com/62459005/78856330-18c2b600-7a44-11ea-914c-826c789b25fb.png)

**Comment by josh146** [comment]
Hi @doperamine --- after installing PennyLane on Google Colab, you will need to restart the runtime. This can be done via the toolbar, or by pressing `ctrl`-`M`:

![image](https://user-images.githubusercontent.com/2959003/78859925-f777bf00-7a6f-11ea-96ef-6ac8e8e20c73.png)

Once the runtime has been restarted, and PennyLane is imported, the `default.qubit` device will be available and ready to use 🙂

**Comment by josh146** [comment]
Let me know if that works for you!

**Comment by doperamine** [comment]
> Let me know if that works for you!

Thank you Josh, it worked :)
