### ISSUE TITLE
Error when trying to import the class 'Operation'

### ISSUE THREAD

**Issue by Tiagoblima** [XanaduAI/pennylane#592]
#### Issue description

When trying to import the class 'Operation' to build a customized gate it rises an import error.

* *Import happens successfully 

* *Actual behaviour:* Import error

* *Reproduces how often:* More than once

* *System information:* 
Name: PennyLane
Version: 0.7.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: c:\users\tiago\anaconda3\envs\q_env\lib\site-packages
Requires: scipy, networkx, numpy, appdirs, toml, semantic-version, autograd
Required-by: PennyLane-qiskit
Platform info:           Windows-10-10.0.18362-SP0
Python version:          3.7.5
Numpy version:           1.18.1
Scipy version:           1.4.1
Installed devices:
- default.gaussian (PennyLane-0.7.0)
- default.qubit (PennyLane-0.7.0)
- expt.tensornet (PennyLane-0.7.0)
- expt.tensornet.tf (PennyLane-0.7.0)
- qiskit.aer (PennyLane-qiskit-0.7.1)
- qiskit.basicaer (PennyLane-qiskit-0.7.1)
- qiskit.ibmq (PennyLane-qiskit-0.7.1)

#### Source code and tracebacks

 File "C:\Users\Tiago\PycharmProjects\QBNN-Variacional\code\plugins\operators\control.py", line 4, in <module>
    from pennylane import Operation
ImportError: cannot import name 'Operation' from 'pennylane' (C:\Users\Tiago\Anaconda3\envs\Q_env\lib\site-packages\pennylane\__init__.py)

**Comment by antalszava** [comment]
Hi @Tiagoblima, thank you so much for your question! :blush: 

This is so because the `Operation` class is not imported explicitly in the `pennylane.__init__.py` file (and is not an attribute of the `pennylane` module while importing).

One thing you could do is to have the import as `from pennylane.operation import Operation`.

Let me know how it works!

**Comment by Tiagoblima** [comment]
Ok. Thank you very much.
